version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: education_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: otash2002
      POSTGRES_DB: education_center  # Sizning bazangiz nomi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - education_network

  api:
    build: .
    container_name: education_api
    environment:
      # URL oxiri POSTGRES_DB bilan bir xil bo'lishi shart
      DATABASE_URL: "postgresql://postgres:otash2002@postgres:5432/education_center?schema=public"
    depends_on:
      - postgres
    ports:
      - "3005:3000"
    networks:
      - education_network

volumes:
  postgres_data:

networks:
  education_network: